#!/usr/bin/env python3
# Copyright (c) 2026 A.I. Hero, Inc.
# All Rights Reserved.

"""Generate CONSISTENCY.md — the before/after view of the harness sweep.

    scripts/consistency.py            # write CONSISTENCY.md
    scripts/consistency.py --stdout   # print instead

GENERATED, deliberately. A hand-maintained status table is a stored result,
and a stored result is a copy — the exact thing this register exists to stamp
out.

Every column comes from data that already exists:

    per-repo mark    <- scripts/audit.py, computed live against origin/main
                        of each repo (--ref; --no-snapshot for the checkouts).
    "How it's made   <- the merged register's rule, which IS the standard.
     consistent"

    There is no "Was broken in" column and no "Reference" note: the register
    names no repos, so a check no longer carries a before-state or an
    exemplar. Everything about WHO is computed this run.

So the table cannot drift from the register: regenerate it and it re-derives.
"""

import argparse
import importlib.util
import pathlib
import sys

HERE = pathlib.Path(__file__).resolve().parent.parent   # the wayfare plugin


# Columns, ordering and results all come from audit.py at run time — never a
# copy here. A five-repo list once lived in this file and dropped three repos.
def short(name):
    """A column header that fits: the fleet's org prefix (FLEET.md `org`, plus
    its `hero-`/`aihero-` style variants) dropped, then truncated. Derived, so
    a new repo needs no entry anywhere; a collision falls back to full names
    in main()."""
    for pre in _prefixes():
        if name.startswith(pre) and len(name) > len(pre):
            name = name[len(pre):]
            break
    return name if len(name) <= 10 else name[:9] + "…"


def _prefixes():
    org = (_ORG or "").lower()
    out = []
    for o in ([org, org.replace("-", "")] if org else []) + ["hero"]:
        out += [o + "-", o + "_"]
    return [p for p in dict.fromkeys(out) if len(p) > 1]


_ORG = None



def load_audit():
    spec = importlib.util.spec_from_file_location("audit", HERE / "scripts" / "audit.py")
    m = importlib.util.module_from_spec(spec)
    # Registered BEFORE exec: the engine loads the fleet's checkers.py at
    # configure time, and that module does `import audit`.
    sys.modules["audit"] = m
    spec.loader.exec_module(m)
    return m


def condense(text, limit=200):
    """One-line summary of a rule block."""
    t = " ".join((text or "").split())
    if len(t) <= limit:
        return t
    cut = t[:limit].rsplit(" ", 1)[0]
    return cut + "…"


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--stdout", action="store_true")
    ap.add_argument("--ref", default="origin/main")
    ap.add_argument("--no-snapshot", action="store_true")
    ap.add_argument("--fleet", default="", help="the fleet root (default: found by walking up from cwd)")
    a = ap.parse_args()

    global _ORG
    audit = load_audit()
    audit.configure(a.fleet or None)
    _ORG = audit.read_fleet(audit.ROOT)[0].get("org") if audit.REGISTER is not None else None
    if audit.REGISTER is None:
        sys.exit("not inside a fleet: CONSISTENCY.md is the fleet's table and lives in its register checkout")
    if not audit.REGISTER.is_dir():
        sys.exit(f"register checkout missing: {audit.REGISTER} — clone it before regenerating its table")
    OUT = audit.REGISTER / "CONSISTENCY.md"
    controls, checks = audit.load_register()
    repos = audit.family_repos()
    if a.no_snapshot:
        matrix, _fails, errors = audit.run_matrix(checks, repos)
    else:
        with audit.snapshot_family(a.ref):
            matrix, _fails, errors = audit.run_matrix(checks, repos)
    if errors:
        sys.exit(f"{len(errors)} checker errors (printed above) — not writing a table built on them")
    rows = [(c, [st for st, _d in cells]) for c, cells in matrix]
    MARK = audit.MARK
    # Two repos rendering to one header would read as one repo; use full
    # names for the whole table rather than let a column lie.
    if len({short(r) for r in repos}) != len(repos):
        globals()["short"] = lambda n: n

    L = []
    L.append("# Consistency — what drifted, and what it looks like now")
    L.append("")
    L.append("<!-- GENERATED by scripts/consistency.py. Do not edit by hand:")
    L.append("     every column is derived, so regenerating re-reads reality.")
    L.append("     A hand-maintained status table is a stored result, and a")
    L.append("     stored result is a copy — the exact failure this register")
    L.append("     exists to stamp out. Run: scripts/consistency.py -->")
    L.append("")
    L.append("Rows are checks. Columns are repos. Regenerate any time:")
    L.append("")
    L.append("```bash")
    L.append("$HERO_SKILLS/scripts/consistency.py     # rewrite this file  (HERO_SKILLS = the plugin checkout)")
    L.append("$HERO_SKILLS/scripts/audit.py --md      # the same results, no history")
    L.append("```")
    L.append("")
    L.append("| | Meaning |")
    L.append("| --- | --- |")
    L.append("| ✅ | complies today |")
    L.append("| ❌ | still drifting |")
    L.append("| – | doesn't apply (no Go, no UI, no image — or `applies_to` names a group this repo is not in) |")
    L.append("| ? | no automated checker — needs a human, not a guess |")
    L.append("")
    L.append("The repo columns are computed live, this run. No check names a")
    L.append("repo, so nothing here is remembered from a previous sweep — a")
    L.append("cell is what the checker found just now.")
    L.append("")

    total = sum(1 for _c, cells in rows for x in cells if x == "FAIL")
    L.append(f"**{total} (check × repo) results failing.** "
             f"{len(checks)} checks under {len(controls)} controls.")
    L.append("")

    last = None
    for c, cells in rows:
        cid = c["control"]
        if cid != last:
            ctl = controls[cid]
            L.append("")
            L.append(f"## {cid} — {ctl['title']} *({ctl['severity']})*")
            L.append("")
            L.append(f"> {condense(ctl.get('intent'), 260)}")
            L.append("")
            L.append("| Check | " + " | ".join(short(r) for r in repos) + " | How it's made consistent |")
            L.append("| --- | " + " | ".join("---" for _ in repos) + " | --- |")
            last = cid

        # No "Was broken in" column and no "Reference:" suffix: the register
        # names no repos, so both had exactly one source and it is gone. Left
        # in, they printed "*(none)*" and "No reference yet — needs a decision"
        # on every row — a column of nothing, and 128 rows each demanding a
        # decision nobody owes. The per-repo cells below already say who fails
        # today, computed this run rather than remembered from the last one.
        how = condense(c.get("rule"), 180)

        L.append(
            f"| **{c['id']}** {c['title']} *({c['scope']})* | "
            + " | ".join(MARK[x] for x in cells)
            + f" | {how} |"
        )

    L.append("")
    L.append("---")
    L.append("")
    L.append("## Reading this honestly")
    L.append("")
    L.append("A `?` is not a pass. It means no checker exists, so the answer is")
    L.append("unknown — reported as unknown rather than guessed.")
    L.append("")
    L.append("**No check names a repo.** A check states what consistent means;")
    L.append("who passes it is this table, computed per run from the repos")
    L.append("FLEET.md lists. Where a consumer got it right first, the fix is")
    L.append("still a backport INTO the template — never a change to the repo")
    L.append("that is already right.")
    L.append("")

    # Emit what this repo's own hooks accept: no run of blank lines
    # (markdownlint MD012) and exactly one trailing newline (end-of-file-fixer).
    # Otherwise every regeneration lands dirty, the hooks rewrite the file, and
    # the generator and its output disagree forever — a drift between the map
    # and the territory, in the one file whose entire purpose is not drifting.
    lines = []
    for line in L:
        if line == "" and lines and lines[-1] == "":
            continue
        lines.append(line)
    while lines and lines[-1] == "":
        lines.pop()

    out = "\n".join(lines) + "\n"
    if a.stdout:
        print(out)
    else:
        OUT.write_text(out)
        print(f"wrote {OUT}  ({len(checks)} checks, {total} failing)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
