#!/usr/bin/env python3
# Copyright (c) 2026 A.I. Hero, Inc.
# All Rights Reserved.

"""Generate CONSISTENCY.md — the before/after view of the harness sweep.

    scripts/consistency.py            # write CONSISTENCY.md
    scripts/consistency.py --stdout   # print instead

GENERATED, deliberately. A hand-maintained status table is a stored result,
and a stored result is a copy — the exact thing this register exists to stamp
out. The port table was copied into seven places and three of them lied.

Every column comes from data that already exists:

    "Was broken in"  <- CHECKS.yaml known_violations, the state when the
                        check was written. This is the BEFORE.
    per-repo mark    <- scripts/audit.py, computed live against origin/main
                        of each repo (--ref; --no-snapshot for the checkouts).
                        This is the AFTER.
    "How it's made   <- CHECKS.yaml rule + reference. The rule IS the
     consistent"        standard; the reference is the repo that already
                        got it right.

So the table cannot drift from the register: regenerate it and it re-derives.
"""

import argparse
import importlib.util
import pathlib
import sys

HERE = pathlib.Path(__file__).resolve().parent.parent   # the hero-skills plugin


# Columns, ordering and results all come from audit.py at run time — never a
# copy here. A five-repo list once lived in this file and dropped three repos.
def short(name):
    """A column header that fits: the org's common prefix dropped, then
    truncated. Derived, so a new repo needs no entry anywhere."""
    for pre in ("hero-", "aihero-"):
        if name.startswith(pre) and len(name) > len(pre):
            name = name[len(pre):]
    return name if len(name) <= 10 else name[:9] + "…"



def load_audit():
    spec = importlib.util.spec_from_file_location("audit", HERE / "scripts" / "audit.py")
    m = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(m)
    return m


def condense(text, limit=200):
    """One-line summary of a rule block."""
    t = " ".join((text or "").split())
    if len(t) <= limit:
        return t
    cut = t[:limit].rsplit(" ", 1)[0]
    return cut + "…"


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--stdout", action="store_true")
    ap.add_argument("--ref", default="origin/main")
    ap.add_argument("--no-snapshot", action="store_true")
    ap.add_argument("--fleet", default="", help="the fleet root (default: found by walking up from cwd)")
    a = ap.parse_args()

    audit = load_audit()
    audit.configure(a.fleet or None)
    if audit.REGISTER is None:
        sys.exit("not inside a fleet: CONSISTENCY.md is the fleet's table and lives in its register checkout")
    OUT = audit.REGISTER / "CONSISTENCY.md"
    controls, checks = audit.load_register()
    repos = audit.family_repos()
    if a.no_snapshot:
        matrix, _fails, errors = audit.run_matrix(checks, repos)
    else:
        with audit.snapshot_family(a.ref):
            matrix, _fails, errors = audit.run_matrix(checks, repos)
    if errors:
        sys.exit(f"{len(errors)} checker errors (printed above) — not writing a table built on them")
    rows = [(c, [st for st, _d in cells]) for c, cells in matrix]
    MARK = audit.MARK

    L = []
    L.append("# Consistency — what drifted, and what it looks like now")
    L.append("")
    L.append("<!-- GENERATED by scripts/consistency.py. Do not edit by hand:")
    L.append("     every column is derived, so regenerating re-reads reality.")
    L.append("     A hand-maintained status table is a stored result, and a")
    L.append("     stored result is a copy — the exact failure this register")
    L.append("     exists to stamp out. Run: scripts/consistency.py -->")
    L.append("")
    L.append("Rows are checks. Columns are repos. Regenerate any time:")
    L.append("")
    L.append("```bash")
    L.append("hero-skills/scripts/consistency.py     # rewrite this file")
    L.append("hero-skills/scripts/audit.py --md      # the same results, no history")
    L.append("```")
    L.append("")
    L.append("| | Meaning |")
    L.append("| --- | --- |")
    L.append("| ✅ | complies today |")
    L.append("| ❌ | still drifting |")
    L.append("| – | doesn't apply (no Go, no UI, no image) |")
    L.append("| ? | no automated checker — needs a human, not a guess |")
    L.append("")
    L.append("**Was broken in** is the state when the check was written — the")
    L.append("*before*. The repo columns are computed live — the *after*. A repo")
    L.append("listed as broken and now ✅ was fixed in this sweep.")
    L.append("")

    total = sum(1 for _c, cells in rows for x in cells if x == "FAIL")
    fixed = 0
    for c, cells in rows:
        kv = set(c.get("known_violations") or [])
        for rn, st in zip(repos, cells):
            if rn in kv and st == "PASS":
                fixed += 1
    L.append(f"**{fixed} (check × repo) results fixed. {total} still failing.** "
             f"{len(checks)} checks under {len(controls)} controls.")
    L.append("")

    last = None
    for c, cells in rows:
        cid = c["control"]
        if cid != last:
            ctl = controls[cid]
            L.append("")
            L.append(f"## {cid} — {ctl['title']} *({ctl['severity']})*")
            L.append("")
            L.append(f"> {condense(ctl.get('intent'), 260)}")
            L.append("")
            L.append("| Check | Was broken in | " + " | ".join(short(r) for r in repos) + " | How it's made consistent |")
            L.append("| --- | --- | " + " | ".join("---" for _ in repos) + " | --- |")
            last = cid

        kv = c.get("known_violations")
        if kv is None:
            was = "*(not recorded)*"
        elif not kv:
            was = "*(none)*"
        else:
            was = ", ".join(short(x) for x in kv)

        how = condense(c.get("rule"), 180)
        ref = c.get("reference")
        if ref and ref != "none":
            how += f" **Reference: {short(ref)}.**"
        elif ref == "none":
            how += " **No reference yet — needs a decision.**"

        L.append(
            f"| **{c['id']}** {c['title']} *({c['scope']})* | {was} | "
            + " | ".join(MARK[x] for x in cells)
            + f" | {how} |"
        )

    L.append("")
    L.append("---")
    L.append("")
    L.append("## Reading this honestly")
    L.append("")
    L.append("A `?` is not a pass. It means no checker exists, so the answer is")
    L.append("unknown — reported as unknown rather than guessed. That distinction")
    L.append("is the whole point: an earlier version of HLT-02 grepped the probe")
    L.append("path for `livez` and reported four false failures, which made it a")
    L.append("naming check wearing a safety check's clothes.")
    L.append("")
    L.append("**The reference is not always the template.** Where a consumer got")
    L.append("it right first, the row names it, and the fix is a backport INTO")
    L.append("the template — never a change to the repo that is already right.")
    L.append("")

    # Emit what this repo's own hooks accept: no run of blank lines
    # (markdownlint MD012) and exactly one trailing newline (end-of-file-fixer).
    # Otherwise every regeneration lands dirty, the hooks rewrite the file, and
    # the generator and its output disagree forever — a drift between the map
    # and the territory, in the one file whose entire purpose is not drifting.
    lines = []
    for line in L:
        if line == "" and lines and lines[-1] == "":
            continue
        lines.append(line)
    while lines and lines[-1] == "":
        lines.pop()

    out = "\n".join(lines) + "\n"
    if a.stdout:
        print(out)
    else:
        OUT.write_text(out)
        print(f"wrote {OUT}  ({len(checks)} checks, {fixed} fixed, {total} failing)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
